[tools]
bat = "0.26.1"
bun = "1.3.5"
codex = "0.98.0"
delta = "0.18.2"
eza = "0.23.4"
fd = "10.3.0"
fx = "39.1.0"
fzf = "0.67.0"
gh = "2.83.1"
ghq = "1.8.0"
go = "1.25.5"
graphite = "1.7.9"
jq = "1.8.1"
lazydocker = "0.24.3"
lazygit = "0.57.0"
lua-language-server = "3.16.2"
neovim = "0.11.5"
node = "24.3.0"
pnpm = "10.14.0"
rg = "15.1.0"
ruff = "0.14.9"
rust-analyzer = "2025-12-15"
sentry = "3.0.0"
stylua = "2.3.1"
temporal = "1.29.1"
uv = "0.8.22"
yarn = "4.12.0"

[settings]
experimental = true
python.uv_venv_auto = true
